### PR TITLE
Added Python

### PR DESCRIPTION
**Pull request by BethanyG**
Added `lib/langauges/python.txt` and `test/langauges/python_test.rb`.

The files are minimal for now.

### CODE REVIEW

**Comment by BethanyG** [comment]
Not clear on what format's needed for the test.  Comment lines within the doc are being picked up.  Is that expected?

**Comment by iHiD** [comment]
Thanks 🙂 

> Comment lines within the doc are being picked up. Is that expected?

Yes, it deletes lines until it finds the first non-matching line.

---

I'd add `import` and `from` to the ignore list too, so the first expected output would be:
```
          WORDS = re.compile("[a-z0-9]+(['][a-z]+)?")

          # Finally, some code:
          def count_words(text):
              return Counter(word.group(0) for word in WORDS.finditer(text.lower()))
```

**Comment by BethanyG** [comment]
Thanks.  The fail was making me crazy.  😅 .  Python files often also have `module` docstrings that look like this with either single or double quotes:
```python
'''
This is a docstring.

And this is the second line of the docstring.
'''
```
But they're hard to identify accurately, and might pick up a multi-line string by mistake, so.

**Comment by iHiD** [comment]
Yeah - we need a solution for docstrings and block comments, but I don't have one yet :)

Thanks!

**Pull request merged**
