### PR TITLE
Extended snippet extractor

### PR DESCRIPTION
**Pull request by joshiraez**
- [x] Created README with initial features
- [x] Constructed rule parser
- [x] Constructed rules's trie factory
- [x] Constructed code parser
- [x] Link everything together

Setting this up to track progress and get initial feedback in case I'm missing any requirements someone needs

### CODE REVIEW

**Comment by joshiraez** [comment]
Mostly finished. I'll be updating some languages to use the extended syntax already, and I'll be updating their tests to use the extended syntax new features.

There is a LOT of rubocop problems with "Conditional branches too long", "Classes too long" on tests and some of the implementation. I'd really need a hand with this because for some things, like the tests, I do need to have those big hashes to create the given state. As for the code, it can be vastly improved, I'm sure, but it will also be really hard to optimize in some places because at its core is a trie-based parser and some conditionals can get clunky.

I also have to remove the hack from the tests where I call in a void context the classes to load them into zeitwerk, but wanted to leave them on for now because they make the tests much more legible without a lot of calls to the classes.

**Comment by ynfle** [comment]
Are we assuming that the code that is dealt with compiles?

**Comment by joshiraez** [comment]
You mean if the result compiles? There are some edge cases where it couldnt: for example were you to put a multiline comment at the beginning of a tabbed line, the extracted line would have no tabs, because the tabs are inside the multiline text that is skipped. If you used a language that requires correct tabbing to compile, that wouldnt compile

Still: Its no really hard to fix, is just something that will clout the code more for something that you would have to go really out of your way to make it happen. Thats the only case I know, too. For all the other cases, the code and tabbing is kept as is, just with emptylines and stripped of the text marked by the rules.

**Comment by iHiD** [comment]
Great work @joshiraez :)

**Pull request merged**
